# Generated by Django 3.2 on 2021-05-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='username',
        ),
        migrations.AddField(
            model_name='room',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='room_avatars/'),
        ),
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.TextField(default='Имя комнаты', max_length=500),
        ),
    ]
