# Generated by Django 3.2 on 2021-05-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userroom', '0002_auto_20210526_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='colors',
        ),
        migrations.AddField(
            model_name='room',
            name='color',
            field=models.CharField(default='#111111', max_length=7),
        ),
    ]
